name: CMake

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  macos-build:
    runs-on: macos-latest
    name: MacOS Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  windows-build:
    runs-on: windows-latest
    name: Windows Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-ninja
        
    - name: Configure CMake
      shell: msys2 {0}
      run: /mingw64/bin/cmake.exe -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON  -DCMAKE_C_COMPILER=/mingw64/bin/clang.exe -DCMAKE_CXX_COMPILER=/mingw64/bin/clang++.exe

    - name: Build
      shell: msys2 {0}
      run: /mingw64/bin/cmake.exe --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}
