name: CMake

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-11, macos-10.15, windows-2022, windows-2019]
        compiler: [clang, gcc]
        exclude:
          - os: macos-11
            compiler: gcc

          - os: macos-10.15
            compiler: gcc

        include:
          - compiler: gcc
            cc: gcc
            cxx: g++

          - compiler: clang
            cc: clang
            cxx: clang++

    name: Build
    runs-on: ${{ matrix.os }}

    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake (No MSYS2)
      if: ${{ matrix.os != 'windows-2022' && matrix.os != 'windows-2019' }}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON

    - name: Build (No MSYS2)
      if: ${{ matrix.os != 'windows-2022' && matrix.os != 'windows-2019' }}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: msys2/setup-msys2@v2
      if: ${{ ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }} && matrix.compiler == 'gcc' }}
      name: Set up MSYS2 (GCC)
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-ninja

    - uses: msys2/setup-msys2@v2
      if: ${{ ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }} && matrix.compiler == 'clang' }}
      name: Set up MSYS2 (Clang)
      with:
        update: true
        install: >-
          base-devel
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-clang
          mingw-w64-x86_64-ninja
        
    - name: Configure CMake (MSYS2)
      if: ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}
      shell: msys2 {0}
      run: /mingw64/bin/cmake.exe -B '${{github.workspace}}/build' -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON  -DCMAKE_C_COMPILER=/mingw64/bin/clang.exe -DCMAKE_CXX_COMPILER=/mingw64/bin/clang++.exe

    - name: Build (MSYS2)
      if: ${{ matrix.os == 'windows-2022' || matrix.os == 'windows-2019' }}
      shell: msys2 {0}
      run: /mingw64/bin/cmake.exe --build '${{github.workspace}}/build' --config ${{env.BUILD_TYPE}}