name: CMake

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  macos-build:
    runs-on: macos-latest
    name: MacOS Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON -DMCKAE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
  windows-build:
    runs-on: windows-latest
    name: Windows Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          cmake
          gcc
        
    - name: Configure CMake
      shell: msys2 {0}
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_dummy_keyboard=ON -DENABLE_dummy_video=ON

    - name: Build
      shell: msys2 {0}
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
