name: CMake

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'logseq/**'
      - '.github/workflows/logseq.yml'

env:
  BUILD_TYPE: Release

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Linux Build

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DENABLE_linux_keyboard=ON -DENABLE_sdl_opengl=ON

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
